version: '3.8'

services:
#### Multiplas instâncias do GTW
  cp-api-gateway-1:
    image: coto/plataform/gateway:latest
    environment:
      FIRST_API_ADDR: http://cp-first-api:8081   
      LOGGING_LEVEL_ROOT: DEBUG
      SERVER_PORT: 8080
      INSTANCE_ID: api-gateway-1
      AUTH_SERVER_ADDR: http://cp-keycloak:8080/auth
      AUTH_SERVER_REALM: coto-plataform
    depends_on:
      - cp-first-api
    #deploy:
    #  replicas: 3  # Sobe 3 instâncias do API Gateway
    networks:
      - coto-plataform-network
      
  cp-api-gateway-2:
    image: coto/plataform/gateway:latest
    environment:
      FIRST_API_ADDR: http://cp-first-api:8081   
      LOGGING_LEVEL_ROOT: DEBUG
      SERVER_PORT: 8082
      INSTANCE_ID: api-gateway-2
      AUTH_SERVER_ADDR: http://cp-keycloak:8080/auth
      AUTH_SERVER_REALM: coto-plataform
    depends_on:
      - cp-first-api
    #deploy:
    #  replicas: 3  # Sobe 3 instâncias do API Gateway
    networks:
      - coto-plataform-network
      
  cp-gtw-cache:
    image: redis:7.4.1
    container_name: gtw-redis-server
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    networks:
      - coto-plataform-network
      
######################################

  cp-load-balancer:
    image: nginx:latest
    container_name: cp-load-balancer
    ports:
      - "80:80"  # Expondo a porta 80 do NGINX na porta 8080 do host
    depends_on:
      - cp-api-gateway-1
      - cp-api-gateway-2
    volumes:
      - ./coto-load-balancer/nginx.conf:/etc/nginx/nginx.conf  # Arquivo de configuração do NGINX
    networks:
      - coto-plataform-network
      
######################################

  cp-keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: cp-keycloak
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_PROXY: edge
      KC_DB: mysql
      KC_DB_URL_HOST: cp-keycloak-db
      KC_DB_URL_PORT: 3306
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      #KC_HOSTNAME_STRICT_HTTPS: "false"
      #KC_HOSTNAME_STRICT_HTTP: "false"
      #KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME: cp-keycloak:8080  # Setado com o endereço interno, dessa forma o acesso não precisa ser via público dos MSs.
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_DEBUG: "true"
      KC_HTTP_RELATIVE_PATH: /auth
    ports:
      - "9090:8080"
    networks:
      - coto-plataform-network

  cp-keycloak-db:
    image: mysql:8.0.23
    container_name: cp-keycloak-db
    environment:
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
    volumes:
      - cp-keycloak-db:/var/lib/mysql
    networks:
      - coto-plataform-network

#######################################
  cp-first-api:
    image: coto/plataform/firstapi:latest
    environment:
      LOGGING_LEVEL_ROOT: INFO
      AUTH_SERVER_ADDR: http://cp-keycloak:8080/auth
      AUTH_SERVER_REALM: coto-plataform
    networks:
      - coto-plataform-network

 
volumes:
  cp-keycloak-db:
    driver: local

networks:
  coto-plataform-network:
    driver: bridge