server:
   port: 8081

spring:
   application:
      name: coto-first-api
   security:
      oauth2:
         resourceserver:
            jwt:
               issuer-uri: ${AUTH_SERVER_ADDR}/realms/${AUTH_SERVER_REALM}
               jwk-set-uri: ${AUTH_SERVER_ADDR}/realms/${AUTH_SERVER_REALM}/protocol/openid-connect/certs      
logging:
   level:
      root: INFO
   pattern:
      console: '%d{"yyyy-MM-dd HH:mm:ss,SSS",UTC} [%-5p] [%-9.9t] %-30c{1}: %X{mdcData}%m%n'
      file: '%d{"yyyy-MM-dd HH:mm:ss,SSS",UTC} [%-5p] [%-9.9t] %-30c{1}: %X{mdcData}%m%n'